name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    # Указываем Node.js 20 для workflow
    runs-on: ubuntu-latest-20  # Изменено на ubuntu-latest-20
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run main.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TOKEN_GPT_API_1: ${{ secrets.TOKEN_GPT_API_1 }} 
      run: |
        set -x  # Включить вывод команд
        python main.py 2>&1 | tee output.log # Сохранение вывода в файл
      
    - name: Загрузить логи
      uses: actions/upload-artifact@v4  # Обновлено до v4
      with:
        name: logs
        path: output.log 
